fix pecl extension

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -109,14 +109,6 @@ install_composer() {
   $bin_path/php -r "unlink('composer-setup.php');"
 }
 
-install_pickle() {
-  local bin_path=$1/bin
-
-  $bin_path/php -r "copy('http://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar', 'pickle.phar');"
-  $bin_path/php -r "exec('chmod +x pickle.phar');"
-  $bin_path/php -r "exec('mv pickle.phar ${bin_path}/pickle');"
-}
-
 construct_configure_options() {
   local install_path=$1
 
@@ -385,16 +377,16 @@ install_pecl_extension() {
 
   echo "Installing PECL extension $extension_name..."
 
-  if $install_path/bin/php $install_path/bin/pickle install -n $extension_name; then
+  if $install_path/bin/pecl install -n $extension_name; then
     echo "PECL extension $extension_name installed successfully."
   else
-    echo "Failed to install $extension_name using pickle. Downloading manually from $extension_get_url..."
+    echo "Failed to install $extension_name using pecl. Downloading manually from $extension_get_url..."
 
     local tmp_dir=$(mktemp -d)
     local file_name="$tmp_dir/$extension_name.tgz"
 
-    curl -L $extension_get_url -o $file_name || exit 1
-    $install_path/bin/php $install_path/bin/pickle install -n $file_name || exit 1
+    curl -L $extension_get_url -o $file_name || esxit 1
+    $install_path/bin/pecl install -n $file_name || exit 1
 
     echo "PECL extension $extension_name installed successfully."
   fi
@@ -417,7 +409,6 @@ create_composer_auth_file() {
 
 install_php "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
 install_composer "$ASDF_INSTALL_PATH"
-install_pickle "$ASDF_INSTALL_PATH"
 
 install_pecl_extension "$ASDF_INSTALL_PATH" "redis" "http://pecl.php.net/get/redis"
 
